name: Coverage
on: [pull_request]
permissions:
  pull-requests: write


jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Generate code coverage
      run: cargo +nightly tarpaulin -p boringtun --verbose --all-features --out xml
    - name: Print PR report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: ./cobertura.xml
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      with:
        recreate: true
        path: code-coverage-results.md
